export const coolCats = [
  {
    semester: "Fall 2018",
    members: [
      {name: "Alma Huselja"},
      {name: "Ariel Chen"},
      {name: "Armaan Valvi"},
      {name: "Austin Wang"},
      {name: "Cara Yi"},
      {name: "Caro de Brito Gottlieb"},
      {name: "Chris Russo"},
      {name: "David Wu"},
      {name: "Debopriyo Biswas"},
      {name: "Demi Zhang"},
      {name: "Emily Geyman"},
      {name: "Gabi Pitten"},
      {name: "Greta Miller"},
      {name: "Handa Chun"},
      {name: "Hayoung Park"},
      {name: "Ishan Levy"},
      {name: "Jake Waksbaum"},
      {name: "Jane Sul"},
      {name: "Jenny Kaufmann"},
      {name: "Kara Bressler"},
      {name: "Lauren Ehehalt"},
      {name: "Laurie Zielinski"},
      {name: "Lilly Quach"},
      {name: "Linh Tran"},
      {name: "Luqman Issah"},
      {name: "Mashad Arora"},
      {name: "Michael Rodriguez"},
      {name: "Michael Tummarello"},
      {name: "Milena Chakraverti-Wuerthwein"},
      {name: "Nadir Noordin"},
      {name: "Natalie Collina"},
      {name: "Peter Schmidt"},
      {name: "Pranaya Anshu"},
      {name: "Sadie Van Vranken"},
      {name: "Sarah Schneider"},
      {name: "Sarah Varghese"},
      {name: "Sebastian Holt"},
      {name: "Serena Mon"},
      {name: "Shirley Klimkiewicz"},
      {name: "Shiye Su"},
      {name: "SiSi Peng"},
      {name: "Sunny Qin"},
      {name: "Will Simon"}
    ]
  },
  {
    semester: "Spring 2019",
    members: [
      {name: "Alma Huselja"},
      {name: "Ariel Chen"},
      {name: "Armaan Valvi"},
      {name: "Austin Wang"},
      {name: "Bilal Mukadam"},
      {name: "Bruce Allen"},
      {name: "Cara Yi"},
      {name: "Caro de Brito Gottlieb"},
      {name: "Celeste Claudio"},
      {name: "Chris Russo"},
      {name: "Conway Niles"},
      {name: "David Wu"},
      {name: "Debopriyo Biswas"},
      {name: "Demi Zhang"},
      {name: "Emily Geyman"},
      {name: "Greta Miller"},
      {name: "Handa Chun"},
      {name: "Hayoung Park"},
      {name: "Ishan Levy"},
      {name: "Jacob Wachspress"},
      {name: "Jane Sul"},
      {name: "Ji-Sung Kim"},
      {name: "Jorge Reyes"},
      {name: "Kara Bressler"},
      {name: "Lauren Ehehalt"},
      {name: "Laurie Zielinski"},
      {name: "Lilly Quach"},
      {name: "Luqman Issah"},
      {name: "Mayisha Sultana"},
      {name: "Michael Rodriguez"},
      {name: "Michael Tummarello"},
      {name: "Milena Chakraverti-Wuerthwein"},
      {name: "Nadir Noordin"},
      {name: "Natalie Collina"},
      {name: "Peter Schmidt"},
      {name: "Pranaya Anshu"},
      {name: "Pulkit Singh"},
      {name: "Sadie Van Vranken"},
      {name: "Sarah Schneider"},
      {name: "Sarah Varghese"},
      {name: "Sebastian Holt"},
      {name: "Serena Mon"},
      {name: "Shirley Klimkiewicz"},
      {name: "Shiye Su"},
      {name: "SiSi Peng"},
      {name: "Will Simon"}
    ]
  }
];